version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: salary
    ports:
      - 5577:5432

  adminer:
    image: adminer
    ports:
      - 5400:8080

  nginx:
    container_name: client
    image: salarycalculationjava_app-client:latest
    ports:
      - 8001:80
      - 443:443
    depends_on:
      - app-server

  app-server:
    container_name: server
    image: salarycalculationjava_app-server:latest
    depends_on:
      - db
    links:
      - db