version: '3.1'

services:

  test-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: salary
    volumes:
      - ./pg_db_init.sql:/docker-entrypoint-initdb.d/pg_db_init.sql
    ports:
      - 5599:5432

  build-container:
    container_name: build-container
    build:
      context: .
      dockerfile: java-build-docker-file
    depends_on:
      - test-db

  ping-test-container:
    container_name: ping-test-container
    build:
      context: .
      dockerfile: ping-test
    depends_on:
      - test-db