version: '3.1'

services:

  test-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: salary
    volumes:
      - ./pg_db_init.sql:/docker-entrypoint-initdb.d/pg_db_init.sql
    ports:
      - 5599:5432

  build-container:
    container_name: build-container
    image: java:openjdk-8-alpine
    working_dir: /opt/salary
    entrypoint:
      - /opt/salary/gradlew
      - app-server:build
    volumes:
      - ./app-server/:/opt/salary/app-server/
      - ./gradle/:/opt/salary/gradle/
      - ./gradlew:/opt/salary/gradlew
      - ./build.gradle:/opt/salary/build.gradle
      - ./settings.gradle:/opt/salary/settings.gradle
    depends_on:
      - test-db
    links:
      - test-db