version: '3.1'

services:

  app-server:
    container_name: server-builder
    build:
      context: .
      dockerfile: build-server-dockerfile

  app-client:
    container_name: client-builder
    build:
      context: .
      dockerfile: build-client-dockerfile