version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5577:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 5400:8080

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx-dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - app-server
    depends_on:
      - app-server

  app-server:
    build:
      context: .
      dockerfile: dockerfiles/app-server-dockerfile
    restart: always
    ports:
      - 8080
    depends_on:
      - db