version: '3.1'

services:

  prod-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: salary
    volumes:
      - ./pg_db_init.sql:/docker-entrypoint-initdb.d/pg_db_init.sql
    ports:
      - 5577:5432

  adminer:
    image: adminer
    ports:
      - 5400:8080

  nginx:
    image: salarycalculationjava_app-client:latest
    ports:
      - 8001:80
      - 443:443

  app-server:
    container_name: prod-container
    image: salarycalculationjava_app-server:latest
    depends_on:
      - prod-db
    links:
      - prod-db