version: '3.1'

services:

  test-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: salary
    volumes:
      - ./pg_db_init.sql:/docker-entrypoint-initdb.d/pg_db_init.sql
    ports:
      - 5599:5432
