version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: salary
    volumes:
      - ./pg_db_init.sql:/docker-entrypoint-initdb.d/pg_db_init.sql
    ports:
      - 5577:5432

  adminer:
    image: adminer
    ports:
      - 5400:8080

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app-client/build/:/opt/app-client/
    ports:
      - 8001:80
      - 443:443
    links:
      - app-server

  app-server:
    container_name: prod-container
    image: salarycalculationjava_build-container:latest
    entrypoint:
      - java
      - -jar
      - /opt/salary/app-server/build/libs/app-server-0.0.1.jar
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db